export APPLICATION="pipelinetemplate"
export DOMAIN_NAME="pipelinetemplate.cucloud.net"
export GITHUB_OWNER="CU-CommunityApps"
export GITHUB_REPO="CodePipeline-Template"
export ALERT_EMAIL=""
export ALERT_PHONE=""
