export APPLICATION="serverlesstemplate"
export DOMAIN_NAME="serverlesstemplate.martysullivan.com"
export GITHUB_OWNER="marty-sullivan"
export GITHUB_REPO="serverless-template"
export ALERT_EMAIL=""
export ALERT_PHONE=""
