export APPLICATION="ServerlessTemplate"
export DOMAIN_NAME="serverless-template.martysullivan.com"
export GITHUB_REPO="https://github.com/marty-sullivan/serverless-template.git"
export ADMIN_EMAIL=""
export ADMIN_PHONE=""
